#!/home/lukas/Anaconda/anaconda3/bin/python
#change path to python if needed


import pandas as pd
import argparse

# Get our command line arguments
parser = argparse.ArgumentParser(description='csv to  LaTeX syntax table')
parser.print_help()
parser.add_argument("origin", help='Ursprungsdatei')
parser.add_argument("save", help='Zieldatei')
parser.add_argument("title" = "Hier Titel eingeben", help='Tabellentitel, der im \\caption-Befehl stehen soll')
args = parser.parse_args()

#load csv to dataframe
df = pd.read_csv(args.origin)
columns = df.columns

#open file
file = open(args.save, "w+")

#write head
file.write("\\begin{table}[!ht]\n\\centering\n\\caption{"+args.title+"}\n\\begin{tabular}{")
for i in range(len(columns)):
    file.write("|c")
file.write("|}\n\\hline\n")

#write column names
i = 1
for column in columns:
    file.write(column)
    if i != len(columns):
        file.write("&")
    else:
        file.write("\\\ \n")
    i += 1
file.write("\\hline\n")
del i

#write table
for index, row in df.iterrows():
    i = 1
    for c in columns:
        file.write(str(row[c]))
        if i != len(columns):
            file.write("&")
        else:
            file.write("\\\ \n")
        i += 1
    file.write("\\hline\n")
del i

#end table
file.write("\\end{tabular}\n\\end{table}\n")

#close file
file.close()

#print confirmation

print("scheint geklappt zu haben")
